### PR TITLE
Resolve Issue SavepointDoesNotExist with module fixture

### PR DESCRIPTION
**Pull request by KimSoungRyoul**
this issue  occurs execution with multiple modules test

each single module test succeeds

#### but
in the case of multiple modules tests  fail
#### `pytest tests` (fail)

---

see this fail log 
commit `remove APIClient()`
https://travis-ci.org/tipsi/pytest-tipsi-django/jobs/603388438?utm_medium=notification&utm_source=github_status

~~~Python
>           transaction.savepoint_rollback(sid)
pytest_tipsi_django/django_fixtures.py:90: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.tox/py37/lib/python3.7/site-packages/django/db/transaction.py:57: in savepoint_rollback
    get_connection(using).savepoint_rollback(sid)
.tox/py37/lib/python3.7/site-packages/django/db/backends/base/base.py:344: in savepoint_rollback
    self._savepoint_rollback(sid)

...
...
E  django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

~~~

---

And this is my local env case  fail log , **when i use MYSQL**    
raise these log
~~~Python
E       django.db.utils.OperationalError: (1305, 'SAVEPOINT s4737629504_x65 does not exist')

../../../../../venv/lib/python3.7/site-packages/MySQLdb/connections.py:224: OperationalError
~~~

---
### it can be resolved just one line modification (auto =True)
~~~Python
@pytest.fixture(scope='module',  autouse=True)
def module_fixture(request, module_transaction):
~~~

if you Approve this PR  
I remove test_with_bug_reproduction1,2.py
And Merge Only these one line
~~~Python
@pytest.fixture(scope='module',  autouse=True)
def module_fixture(request, module_transaction):
~~~

### CODE REVIEW

**Comment by KimSoungRyoul** [comment]
as you know below diagram  is something different to travis failed log

i did not reproduce these issue perfectly
but when i try debuging & break with logging , i figure out these issue

#### I not completely sure below diagram flow

#### but it is sure` module_fixture (autouse=True )` resolve these issue
---

### As Is ->
스크린샷 2019-10-27 오전 11 04 05

---
### To Be ->
스크린샷 2019-10-27 오전 11 05 48

**Comment by KimSoungRyoul** [comment]
And By the way  

this project would need QuickStart Maual

with 
* don't  use mixed `module_fixture` & `module_transaction`  in project
* how to use client_fixture
* blablabla~~~

**Comment by cybergrind** [comment]
@KimSoungRyoul it is broken not because of that. You shouldn't use `module_fixture` (and `function_fixture` as well) it is broken and the only way you can use `module_transaction` is only inside `with module_transaction` block. Otherwise, you can get that error when transactions is rolled back before we're expecting this.

Moreover, `module_fixture` isn't working in a way you may think. It is just broken and wasn't removed because we needed to cleanup some old code, probably it is a good time to do that. The same applies to all attempts to avoid three line setup (`with module_transaction`). We have a way to move it to decorator but it is really ugly. If you rewrite your code to blocks that are using `with module_transaction` instead of `module_fixture` everything will just work.

**Comment by cybergrind** [comment]
Fix for your case is removing all function-level `@pytest.mark.django_db` and:

```@pytest.fixture(autouse=True, scope='module')
def this_is_module_fixture(module_transaction, request):
    # create what you want in this module
    with module_transaction(request.fixturename):
        yield User.objects.create(username='this user available in module level')
```

**Comment by jongsoobae** [comment]
@cybergrind

Can you explain why you deprecated module_fixture?

It is convienient compared to with module_transaction. . .

**Comment by cybergrind** [comment]
@jongsoobae it is just broken and doesn't do what do you think. These fixtures were created by a lazy developer who found it easier to use and thought that it is inconvenient to write 3 additional lines per fixture. But it never worked and when we found out that we have tried to fix it - it took way more time than you might think and involved such techniques that we don't wont to use at all.

If you want more details: fixtures don't work as decorators, you cannot guarantee when it starts (just that will be started before fixture that requires it and when it ends) and it will be shared between different fixtures. As soon as two different fixtures will create data in a single scope and this transaction won't be rolled back correctly you're going to have inconsistent data where you cannot guarantee that there are no data from previous test's fixtures (imaging test1 has fixture1 and fixture2, and test2 has only fixture1 - but because they're sharing module_fixture - you're going to get data from both because it wouldn't be rolled back). So you will end with moving this to the decorators. But it actually isn't that easy to write such decorator, you may try to do that if you have time :D

**Pull request closed without merging**
